-- Bulk-seeds 200 popular mobile/cross-platform games as official game
-- communities, so staff don't have to add each one by hand through
-- Admin > Create game. Mirrors exactly what admin_create_game() writes:
-- is_official = true, is_private = false, require_approval = false,
-- member_count defaults to 0. Safe to re-run — ON CONFLICT (slug) skips
-- any game that already exists.
--
-- Categories use the same values as the "Create game" screen's dropdown
-- (fps, battle_royale, sports, moba, sandbox, other). Many titles below
-- were bucketed into 'other' for lack of a closer fit — staff can
-- re-categorize any of them later from Admin > Manage games.

insert into public.communities
  (name, slug, game_name, category, platforms, is_official, is_private, require_approval, member_count)
select
  g.name,
  g.slug,
  g.name,
  g.category,
  array['mobile']::text[],
  true,
  false,
  false,
  0
from (
  values
  ('PUBG Mobile', 'pubg-mobile', 'battle_royale'),
  ('Free Fire', 'free-fire', 'battle_royale'),
  ('Call of Duty: Mobile', 'call-of-duty-mobile', 'fps'),
  ('Fortnite', 'fortnite', 'battle_royale'),
  ('Apex Legends Mobile', 'apex-legends-mobile', 'battle_royale'),
  ('Arena Breakout', 'arena-breakout', 'battle_royale'),
  ('Blood Strike', 'blood-strike', 'battle_royale'),
  ('Standoff 2', 'standoff-2', 'fps'),
  ('Critical Ops', 'critical-ops', 'fps'),
  ('Modern Combat 5', 'modern-combat-5', 'fps'),
  ('Shadowgun Legends', 'shadowgun-legends', 'fps'),
  ('Badlanders', 'badlanders', 'battle_royale'),
  ('T3 Arena', 't3-arena', 'fps'),
  ('Warface GO', 'warface-go', 'fps'),
  ('Special Forces Group 2', 'special-forces-group-2', 'fps'),
  ('Bullet Echo', 'bullet-echo', 'fps'),
  ('Pixel Gun 3D', 'pixel-gun-3d', 'fps'),
  ('Zooba', 'zooba', 'battle_royale'),
  ('Guns of Boom', 'guns-of-boom', 'fps'),
  ('MaskGun', 'maskgun', 'fps'),
  ('Mobile Legends: Bang Bang', 'mobile-legends-bang-bang', 'moba'),
  ('Arena of Valor', 'arena-of-valor', 'moba'),
  ('League of Legends: Wild Rift', 'league-of-legends-wild-rift', 'moba'),
  ('Pokémon UNITE', 'pok-mon-unite', 'moba'),
  ('Brawl Stars', 'brawl-stars', 'moba'),
  ('Clash of Clans', 'clash-of-clans', 'sandbox'),
  ('Clash Royale', 'clash-royale', 'sandbox'),
  ('Boom Beach', 'boom-beach', 'sandbox'),
  ('Lords Mobile', 'lords-mobile', 'sandbox'),
  ('Rise of Kingdoms', 'rise-of-kingdoms', 'sandbox'),
  ('State of Survival', 'state-of-survival', 'sandbox'),
  ('Whiteout Survival', 'whiteout-survival', 'sandbox'),
  ('Last Shelter: Survival', 'last-shelter-survival', 'sandbox'),
  ('Age of Origins', 'age-of-origins', 'sandbox'),
  ('Top War', 'top-war', 'sandbox'),
  ('Art of War 3', 'art-of-war-3', 'sandbox'),
  ('Iron Marines', 'iron-marines', 'sandbox'),
  ('Auto Chess', 'auto-chess', 'moba'),
  ('Teamfight Tactics', 'teamfight-tactics', 'moba'),
  ('Chess.com', 'chess-com', 'other'),
  ('Genshin Impact', 'genshin-impact', 'other'),
  ('Tower of Fantasy', 'tower-of-fantasy', 'other'),
  ('Diablo Immortal', 'diablo-immortal', 'other'),
  ('Black Desert Mobile', 'black-desert-mobile', 'other'),
  ('Ragnarok M: Eternal Love', 'ragnarok-m-eternal-love', 'other'),
  ('RuneScape Mobile', 'runescape-mobile', 'other'),
  ('Old School RuneScape', 'old-school-runescape', 'other'),
  ('Albion Online', 'albion-online', 'sandbox'),
  ('Lineage 2: Revolution', 'lineage-2-revolution', 'other'),
  ('Perfect World Mobile', 'perfect-world-mobile', 'other'),
  ('V4', 'v4', 'other'),
  ('MIR4', 'mir4', 'other'),
  ('Ni no Kuni: Cross Worlds', 'ni-no-kuni-cross-worlds', 'other'),
  ('Blade & Soul Revolution', 'blade-soul-revolution', 'other'),
  ('Toram Online', 'toram-online', 'other'),
  ('Adventure Quest 3D', 'adventure-quest-3d', 'other'),
  ('EVE Echoes', 'eve-echoes', 'sandbox'),
  ('Honkai: Star Rail', 'honkai-star-rail', 'other'),
  ('Wuthering Waves', 'wuthering-waves', 'other'),
  ('Zenless Zone Zero', 'zenless-zone-zero', 'other'),
  ('Asphalt 9: Legends', 'asphalt-9-legends', 'sports'),
  ('Asphalt 8: Airborne', 'asphalt-8-airborne', 'sports'),
  ('Need for Speed: No Limits', 'need-for-speed-no-limits', 'sports'),
  ('Real Racing 3', 'real-racing-3', 'sports'),
  ('Mario Kart Tour', 'mario-kart-tour', 'sports'),
  ('CarX Drift Racing 2', 'carx-drift-racing-2', 'sports'),
  ('Beach Buggy Racing 2', 'beach-buggy-racing-2', 'sports'),
  ('F1 Mobile Racing', 'f1-mobile-racing', 'sports'),
  ('CSR Racing 2', 'csr-racing-2', 'sports'),
  ('eFootball 2024', 'efootball-2024', 'sports'),
  ('EA Sports FC Mobile', 'ea-sports-fc-mobile', 'sports'),
  ('Dream League Soccer 2024', 'dream-league-soccer-2024', 'sports'),
  ('Basketball Arena', 'basketball-arena', 'sports'),
  ('NBA 2K Mobile', 'nba-2k-mobile', 'sports'),
  ('NBA LIVE Mobile', 'nba-live-mobile', 'sports'),
  ('Tennis Clash', 'tennis-clash', 'sports'),
  ('Golf Clash', 'golf-clash', 'sports'),
  ('Mini Golf King', 'mini-golf-king', 'sports'),
  ('8 Ball Pool', '8-ball-pool', 'sports'),
  ('Carrom Pool', 'carrom-pool', 'sports'),
  ('Among Us', 'among-us', 'other'),
  ('Roblox', 'roblox', 'sandbox'),
  ('Minecraft', 'minecraft', 'sandbox'),
  ('Fall Guys (Mobile via cloud/Epic)', 'fall-guys-mobile-via-cloud-epic', 'other'),
  ('Stumble Guys', 'stumble-guys', 'other'),
  ('PK XD', 'pk-xd', 'other'),
  ('Avakin Life', 'avakin-life', 'other'),
  ('IMVU', 'imvu', 'other'),
  ('Rec Room', 'rec-room', 'other'),
  ('Play Together', 'play-together', 'other'),
  ('Sky: Children of the Light', 'sky-children-of-the-light', 'other'),
  ('Tomodachi Life style social games', 'tomodachi-life-style-social-games', 'other'),
  ('Goofball Nations', 'goofball-nations', 'other'),
  ('UNO!', 'uno', 'other'),
  ('Ludo King', 'ludo-king', 'other'),
  ('Ludo Club', 'ludo-club', 'other'),
  ('Parchisi STAR', 'parchisi-star', 'other'),
  ('Domino Go', 'domino-go', 'other'),
  ('Yahtzee With Buddies', 'yahtzee-with-buddies', 'other'),
  ('Monopoly GO!', 'monopoly-go', 'other'),
  ('Marvel Snap', 'marvel-snap', 'other'),
  ('Hearthstone', 'hearthstone', 'other'),
  ('Yu-Gi-Oh! Master Duel', 'yu-gi-oh-master-duel', 'other'),
  ('Yu-Gi-Oh! Duel Links', 'yu-gi-oh-duel-links', 'other'),
  ('Legends of Runeterra', 'legends-of-runeterra', 'other'),
  ('Magic: The Gathering Arena', 'magic-the-gathering-arena', 'other'),
  ('Pokémon TCG Live', 'pok-mon-tcg-live', 'other'),
  ('Gwent: Rogue Mage', 'gwent-rogue-mage', 'other'),
  ('Clash of Cards', 'clash-of-cards', 'other'),
  ('Exploding Kittens', 'exploding-kittens', 'other'),
  ('Catan Universe', 'catan-universe', 'other'),
  ('Ticket to Ride', 'ticket-to-ride', 'other'),
  ('Carcassonne', 'carcassonne', 'other'),
  ('Scrabble GO', 'scrabble-go', 'other'),
  ('Word With Friends 2', 'word-with-friends-2', 'other'),
  ('Phase 10: World Tour', 'phase-10-world-tour', 'other'),
  ('Gin Rummy Stars', 'gin-rummy-stars', 'other'),
  ('Spades Plus', 'spades-plus', 'other'),
  ('Euchre 3D', 'euchre-3d', 'other'),
  ('Backgammon Lord of the Board', 'backgammon-lord-of-the-board', 'other'),
  ('Shadow Fight 4: Arena', 'shadow-fight-4-arena', 'other'),
  ('Mortal Kombat', 'mortal-kombat', 'other'),
  ('Injustice 2', 'injustice-2', 'other'),
  ('WWE Mayhem', 'wwe-mayhem', 'other'),
  ('Street Fighter IV CE', 'street-fighter-iv-ce', 'other'),
  ('Brawlhalla', 'brawlhalla', 'other'),
  ('Sonic Forces', 'sonic-forces', 'other'),
  ('PAC-MAN GEO', 'pac-man-geo', 'other'),
  ('Crossy Road', 'crossy-road', 'other'),
  ('Fruit Ninja Classic+', 'fruit-ninja-classic', 'other'),
  ('Worms Zone .io', 'worms-zone-io', 'other'),
  ('Paper.io 2', 'paper-io-2', 'other'),
  ('Hole.io', 'hole-io', 'other'),
  ('Slither.io', 'slither-io', 'other'),
  ('Agar.io', 'agar-io', 'other'),
  ('Snake.io', 'snake-io', 'other'),
  ('Tank Stars', 'tank-stars', 'other'),
  ('Bowmasters', 'bowmasters', 'other'),
  ('Archero', 'archero', 'other'),
  ('Hero Hunters', 'hero-hunters', 'other'),
  ('Ark: Survival Evolved', 'ark-survival-evolved', 'sandbox'),
  ('Durango: Wild Lands legacy style', 'durango-wild-lands-legacy-style', 'sandbox'),
  ('Last Day on Earth: Survival', 'last-day-on-earth-survival', 'sandbox'),
  ('Grim Soul', 'grim-soul', 'sandbox'),
  ('Jurassic Survival', 'jurassic-survival', 'sandbox'),
  ('LifeAfter', 'lifeafter', 'sandbox'),
  ('Dawn of Titans', 'dawn-of-titans', 'sandbox'),
  ('Cyber Hunter', 'cyber-hunter', 'fps'),
  ('Creative Destruction', 'creative-destruction', 'fps'),
  ('Hopeless Land', 'hopeless-land', 'battle_royale'),
  ('Blue Archive', 'blue-archive', 'other'),
  ('Fate/Grand Order', 'fate-grand-order', 'other'),
  ('Azur Lane', 'azur-lane', 'other'),
  ('Alchemy Stars', 'alchemy-stars', 'other'),
  ('Arknights', 'arknights', 'other'),
  ('Punishing: Gray Raven', 'punishing-gray-raven', 'other'),
  ('Epic Seven', 'epic-seven', 'other'),
  ('Summoners War', 'summoners-war', 'other'),
  ('RAID: Shadow Legends', 'raid-shadow-legends', 'other'),
  ('Hero Wars', 'hero-wars', 'other'),
  ('Golf Battle', 'golf-battle', 'sports'),
  ('Mini Basketball', 'mini-basketball', 'sports'),
  ('Score! Match', 'score-match', 'sports'),
  ('Head Ball 2', 'head-ball-2', 'sports'),
  ('Rumble Hockey', 'rumble-hockey', 'sports'),
  ('Volleyball Arena', 'volleyball-arena', 'sports'),
  ('Bowling King', 'bowling-king', 'sports'),
  ('Archery King', 'archery-king', 'sports'),
  ('Darts Club', 'darts-club', 'sports'),
  ('Billiards City online modes', 'billiards-city-online-modes', 'sports'),
  ('Blockudoku online', 'blockudoku-online', 'other'),
  ('QuizUp legacy alternatives', 'quizup-legacy-alternatives', 'other'),
  ('Trivia Crack', 'trivia-crack', 'other'),
  ('HQ Trivia style apps', 'hq-trivia-style-apps', 'other'),
  ('SongPop Classic', 'songpop-classic', 'other'),
  ('SongPop Party', 'songpop-party', 'other'),
  ('Sketchful style drawing games', 'sketchful-style-drawing-games', 'other'),
  ('Gartic.io', 'gartic-io', 'other'),
  ('Skribbl style apps', 'skribbl-style-apps', 'other'),
  ('Pinturillo 2', 'pinturillo-2', 'other'),
  ('Supercell Squad Busters', 'supercell-squad-busters', 'other'),
  ('Wild Blood', 'wild-blood', 'other'),
  ('Order & Chaos Online', 'order-chaos-online', 'other'),
  ('Dark Nemesis', 'dark-nemesis', 'other'),
  ('MU Origin 3', 'mu-origin-3', 'other'),
  ('Saint Seiya Legend of Justice', 'saint-seiya-legend-of-justice', 'other'),
  ('One Punch Man: World', 'one-punch-man-world', 'other'),
  ('Solo Leveling: Arise', 'solo-leveling-arise', 'other'),
  ('Dragon Ball Legends', 'dragon-ball-legends', 'other'),
  ('Dragon Ball Z Dokkan Battle', 'dragon-ball-z-dokkan-battle', 'other'),
  ('Naruto x Boruto Ninja Voltage', 'naruto-x-boruto-ninja-voltage', 'other'),
  ('Bleach: Brave Souls', 'bleach-brave-souls', 'other'),
  ('Pokémon GO', 'pok-mon-go', 'other'),
  ('Monster Hunter Now', 'monster-hunter-now', 'other'),
  ('Pikmin Bloom', 'pikmin-bloom', 'other'),
  ('Harry Potter: Magic Awakened', 'harry-potter-magic-awakened', 'other'),
  ('MARVEL Future Fight', 'marvel-future-fight', 'other'),
  ('MARVEL Contest of Champions', 'marvel-contest-of-champions', 'other'),
  ('Star Wars: Galaxy of Heroes', 'star-wars-galaxy-of-heroes', 'other'),
  ('Disney Mirrorverse', 'disney-mirrorverse', 'other')
) as g(name, slug, category)
on conflict (slug) do nothing;
